version: 2.1
jobs:
  build-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: |
               sudo yum install -y smartmet-utils-devel
               sudo yum upgrade -y git
      - run:
          name: Create build configuration
          command: |
               smartbuild --create-workspace --default-config --remove-module smartmet-plugin-edr --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          name: Build new release RPMs
          command: |
             mkdir -p workspace/export/smartmet-open/rhel/7 workspace/log
             smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - run:
          name: Archive newly built RPM packages and build/install related log files
          command: |
             ( cd workspace/export && tar cvf new-rhel7-release-rpms-$(date +%Y%m%d_%H%M).tar * )
             ( cd workspace/log && tar cJvf rhel7-build-logs-$(date +%Y%m%d_%H%M).tar.xz * )
             mkdir -p artifacts
             mv -v workspace/export/*.tar workspace/log/*.tar.xz artifacts/
             ls -l artifacts
          when: always
      - store_artifacts:
          path: artifacts
  build-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: sudo yum install -y smartmet-utils-devel
      - run:
          name: Create build configuration
          command: |
               smartbuild --create-workspace --default-config --remove-module smartmet-plugin-edr --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          name: Build new release RPMs
          command: |
             mkdir -p workspace/export/smartmet-open/rhel/8 workspace/log
             smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - run:
          name: Archive newly built RPM packages and build/install related log files
          command: |
             ( cd workspace/export && tar cvf new-rhel8-release-rpms-$(date +%Y%m%d_%H%M).tar *)
             ( cd workspace/log && tar cJvf rhel8-build-logs-$(date +%Y%m%d_%H%M).tar.xz *)
             mkdir -p artifacts
             mv -v workspace/export/*.tar workspace/log/*.tar.xz artifacts/
             ls -l artifacts
          when: always
      - store_artifacts:
          path: artifacts
  build-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: sudo yum install -y smartmet-utils-devel
      - run:
          name: Create build configuration
          command: |
               smartbuild --create-workspace --default-config --remove-module smartmet-plugin-edr --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          name: Build new release RPMs
          command: |
             mkdir -p workspace/export/smartmet-open/rhel/9 workspace/log
             smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - run:
          name: Archive newly built RPM packages and build/install related log files
          command: |
             ( cd workspace/export && tar cvf new-rhel9-release-rpms-$(date +%Y%m%d_%H%M).tar *)
             ( cd workspace/log && tar cJvf rhel9-build-logs-$(date +%Y%m%d_%H%M).tar.xz *)
             mkdir -p artifacts
             mv -v workspace/export/*.tar workspace/log/*.tar.xz artifacts/
             ls -l artifacts
          when: always
      - store_artifacts:
          path: artifacts

workflows:
  version: 2.1
  build-release-rpms:
    when:
        and:
          - equal [ scheduled_pipeline, << pipeline.trigger_source >> ]
          - equal [ "release-rpm-build", << pipeline.schedule.name >> ]
    jobs:
      - build-rhel7
      - build-rhel8
      - build-rhel9
