version: 2.1
jobs:
  build-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: sudo yum install -y smartmet-utils-devel
      - run:
          name: Create build configuration
          command: |
               smartbuild --create-workspace --default-config --remove-module smartmet-plugin-edr --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          name: Build new release RPMs
          command: |
             mkdir -p workspace/export/smartmet-open/rhel/9/beta workspace/log
             smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - run:
          name: Archive newly built RPM packages and build/install related log files
          command: |
             ( cd workspace/export && tar cvf ../../built-packages.tar *)
             ( cd workspace/log && tar cJvf ../../logs-files.tar.xz *)
      - store_artifacts:
          path: built-packages.tar
      - store_artifacts:
          path: logs-files.tar.xz

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel9
