version: 2.1
jobs:
  build-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: sudo yum install -y smartmet-utils-devel
      - run:
          name: Create build configuration
          command: smartbuild --create-workspace --add-module smartmet-library-macgyver --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          command: smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - store_artifacts:
          path: ./workspace/export/*
          destination: built-rhel8-rpms
      - store_artifacts:
          path: ./workspace/log/*
          destination: rhel8-build-logs
workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel8
