version: 2.1
jobs:
  build-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install smartmet-utils-devel
          command: sudo yum install -y smartmet-utils-devel
      - run:
          name: Create build configuration
          command: |
               smartbuild --create-workspace --default-config --dump-config >smartbuild.json
      - run:
          name: Create local mirrors of smartmet repos (open sources only)
          command: smartbuild --config smartbuild.json --recursive --update --https
      - run:
          name: Build new release RPMs
          command: |
             pwd
             ls -l
             mkdir -p workspace/export/smartmet-open/rhel/8/beta workspace/export/log
             smartbuild --config smartbuild.json --builddep --recursive --local --release-rpms --separate-logs
      - store_artifacts:
          path: ./workspace/log
      - persist_to_workspace:
          root: /dist
          path: ./workspace/export/*
  upload-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo yum -y install dnf
            sudo dnf -y install python3-pip
            pip3 install awscli --upgrade --user
      - run:
          name: Sync artifacts to S3
          command: |
            export PATH=$PATH:~/.local/bin
            aws s3 cp /dist s3://fmi-smartmet-cicd-beta/release-rpms/ --recursive --exclude '*' --include '*.rpm'
workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel8
      - upload-rhel8:
          context: fmi-global
          requires:
            - build-rhel8
